### ISSUE TITLE
Reuse of comms not working

### ISSUE THREAD

**Issue by danholdaway** [JCSDA-internal/fckit#5]
Line 1106 of fckit_mpi.py is commented out and this seems to be causing an issue with reusing comms. The following pseudo code does not work for me:

```type(fckit_mpi_comm) :: f_comm
type(fckit_mpi_comm) :: f_comm_new

call mpi_comm_split(f_comm%communicator(), geom%ntile, f_comm%rank(), commnew, ierr)
f_comm_new = fckit_mpi_comm(commnew)

call f_comm_new%delete()
call MPI_Comm_free(commtile, ierr)

call mpi_comm_split(f_comm%communicator(), geom%ntile, f_comm%rank(), commnew, ierr)
f_comm_new = fckit_mpi_comm(commnew)
print*, f_comm_new%rank()
```

This is because the second f_comm_new = fckit_mpi_comm(commnew) does not return a valid pointer. My guess is this because nothing really happens in %delete so the second fckit_mpi_comm(commnew) call does not set a pointer to the comm created in the second mpi_comm_split since it thinks it already exists but call MPI_Comm_free(commtile, ierr) removed the place it needs to point to. Interestingly only GCC compilers pick up on this issue.

If I uncomment line 1106 then I get an immediate seg fault in applications

This may get to be more of a problem as we move to doing things with split comms in the future.

@mmiesch perhaps you could pass this on to the fckit folks? I can't post issues over there. The same line is commented out in their fckit_mpi.fypp

**Comment by mmiesch** [comment]
Ok - I will take a look.  I'm having more issues with the latest develop branch of fckit.
